import React from 'react';
import './style.css';

class PrivacyPolicy extends React.Component {
	render() {
		return (
			<div className="container">
				<h1 className="pp_h1 pp_main">Privacy Policy</h1>
				<p>Last updated: May 10, 2021</p>
				<p>
					This Privacy Policy describes Our policies and procedures on the collection, use
					and disclosure of your information when you use the Service and tells you about
					your privacy rights and how the law protects you.
				</p>
				<p>
					We use your Personal data to provide and improve the Service. By using the
					Service, you agree to the collection and use of information in accordance with
					this Privacy Policy.
				</p>
				<h2 className="pp_h2">Interpretation</h2>

				<p>
					The words of which the initial letter is capitalized have meanings defined under
					the following conditions. The following definitions shall have the same meaning
					regardless of whether they appear in singular or in plural.
				</p>
				<h2 className="pp_h2">Definitions</h2>
				<p>For the purposes of this Privacy Policy:</p>
				<ul>
					<li className="pp_li">
						<p>
							<strong>Account</strong> means a unique account created for you to
							access our Service or parts of our Service.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>Company</strong> (referred to as either &quot;the Company&quot;,
							&quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement)
							refers to medipro, The LNM Institute of Information Technology.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>Cookies</strong> are small files that are placed on your
							computer, mobile device or any other device by a website, containing the
							details of your browsing history on that website among its many uses.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>Country</strong> refers to: Rajasthan, India
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>Device</strong> means any device that can access the Service
							such as a computer, a cellphone or a digital tablet.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>Personal Data</strong> is any information that relates to an
							identified or identifiable individual.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>Service</strong> refers to the Website.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>Service Provider</strong> means any natural or legal person who
							processes the data on behalf of the Company. It refers to third-party
							companies or individuals employed by the Company to facilitate the
							Service, to provide the Service on behalf of the Company, to perform
							services related to the Service or to assist the Company in analyzing
							how the Service is used.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>Third-party Social Media Service</strong> refers to any website
							or any social network website through which a User can log in or create
							an account to use the Service.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>Usage Data</strong> refers to data collected automatically,
							either generated by the use of the Service or from the Service
							infrastructure itself (for example, the duration of a page visit).
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>Website</strong> refers to medipro, accessible from{' '}
							<a href="medipro.com" rel="external nofollow noopener" target="_blank">
								medipro.com
							</a>
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>you</strong> means the individual accessing or using the
							Service, or the company, or other legal entity on behalf of which such
							individual is accessing or using the Service, as applicable.
						</p>
					</li>
				</ul>
				<h2 className="pp_h2">Types of Data Collected</h2>
				<h3 className="pp_h3">Personal Data</h3>
				<p>
					While using Our Service, We may ask you to provide Us with certain personally
					identifiable information that can be used to contact or identify you. Personally
					identifiable information may include, but is not limited to:
				</p>
				<ul>
					<li className="pp_li">
						<p>Email address</p>
					</li>
					<li className="pp_li">
						<p>First name and last name</p>
					</li>
					<li className="pp_li">
						<p>Usage Data</p>
					</li>
				</ul>
				<h3 className="pp_h3">Usage Data</h3>
				<p>Usage Data is collected automatically when using the Service.</p>
				<p>
					Usage Data may include information such as your Device's Internet Protocol
					address (e.g. IP address), browser type, browser version, the pages of our
					Service that you visit, the time and date of your visit, the time spent on those
					pages, unique device identifiers and other diagnostic data.
				</p>
				<p>
					When you access the Service by or through a mobile device, We may collect
					certain information automatically, including, but not limited to, the type of
					mobile device you use, your mobile device unique ID, the IP address of your
					mobile device, your mobile operating system, the type of mobile Internet browser
					you use, unique device identifiers and other diagnostic data.
				</p>
				<p>
					We may also collect information that your browser sends whenever you visit our
					Service or when you access the Service by or through a mobile device.
				</p>
				<h3 className="pp_h3">Information from Third-Party Social Media Services</h3>
				<p>
					The Company allows you to create an account and log in to use the Service
					through the following Third-party Social Media Services:
				</p>
				<ul>
					<li className="pp_li">Google</li>
					<li className="pp_li">Facebook</li>
					<li className="pp_li">Twitter</li>
				</ul>

				<p>
					If you decide to register through or otherwise grant us access to a Third-Party
					Social Media Service, We may collect Personal data that is already associated
					with your Third-Party Social Media Service's account, such as your name, your
					email address, your activities or your contact list associated with that
					account.
				</p>
				<p>
					you may also have the option of sharing additional information with the Company
					through your Third-Party Social Media Service's account. If you choose to
					provide such information and Personal Data, during registration or otherwise,
					you are giving the Company permission to use, share, and store it in a manner
					consistent with this Privacy Policy.
				</p>
				<h3 className="pp_h3">Tracking Technologies and Cookies</h3>
				<p>
					We use Cookies and similar tracking technologies to track the activity on Our
					Service and store certain information. Tracking technologies used are beacons,
					tags, and scripts to collect and track information and to improve and analyze
					Our Service. The technologies We use may include:
				</p>
				<ul>
					<li className="pp_li">
						<strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed
						on your Device. you can instruct your browser to refuse all Cookies or to
						indicate when a Cookie is being sent. However, if you do not accept Cookies,
						you may not be able to use some parts of our Service. Unless you have
						adjusted your browser setting so that it will refuse Cookies, our Service
						may use Cookies.
					</li>
					<li className="pp_li">
						<strong>Flash Cookies.</strong> Certain features of our Service may use
						local stored objects (or Flash Cookies) to collect and store information
						about your preferences or your activity on our Service. Flash Cookies are
						not managed by the same browser settings as those used for Browser Cookies.
						For more information on how you can delete Flash Cookies, please read &quot;
					</li>
					<li className="pp_li">
						<strong>Web Beacons.</strong> Certain sections of our Service and our emails
						may contain small electronic files known as web beacons (also referred to as
						clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for
						example, to count users who have visited those pages or opened an email and
						for other related website statistics (for example, recording the popularity
						of a certain section and verifying system and server integrity).
					</li>
				</ul>
				<p>
					Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent
					Cookies remain on your personal computer or mobile device when you go offline,
					while Session Cookies are deleted as soon as you close your web browser.
				</p>
				<p>We use both Session and Persistent Cookies for the purposes set out below:</p>
				<ul>
					<li className="pp_li">
						<p>
							<strong>Necessary / Essential Cookies</strong>
						</p>
						<p>Type: Session Cookies</p>
						<p>Administered by: Us</p>
						<p>
							Purpose: These Cookies are essential to provide you with services
							available through the Website and to enable you to use some of its
							features. They help to authenticate users and prevent fraudulent use of
							user accounts. Without these Cookies, the services that you have asked
							for cannot be provided, and We only use these Cookies to provide you
							with those services.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>Cookies Policy / Notice Acceptance Cookies</strong>
						</p>
						<p>Type: Persistent Cookies</p>
						<p>Administered by: Us</p>
						<p>
							Purpose: These Cookies identify if users have accepted the use of
							cookies on the Website.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>Functionality Cookies</strong>
						</p>
						<p>Type: Persistent Cookies</p>
						<p>Administered by: Us</p>
						<p>
							Purpose: These Cookies allow us to remember choices you make when you
							use the Website, such as remembering your login details or language
							preference. The purpose of these Cookies is to provide you with a more
							personal experience and to avoid you having to re-enter your preferences
							every time you use the Website.
						</p>
					</li>
				</ul>
				<p>
					For more information about the cookies we use and your choices regarding
					cookies, please visit our Cookies Policy or the Cookies section of our Privacy
					Policy.
				</p>
				<h2 className="pp_h2">Use of your Personal Data</h2>
				<p>The Company may use Personal Data for the following purposes:</p>
				<ul>
					<li className="pp_li">
						<p>
							<strong>To provide and maintain our Service</strong>, including to
							monitor the usage of our Service.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>To manage your Account:</strong> to manage your registration as
							a user of the Service. The Personal Data you provide can give you access
							to different functionalities of the Service that are available to you as
							a registered user.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>For the performance of a contract:</strong> the development,
							compliance and undertaking of the purchase contract for the products,
							items or services you have purchased or of any other contract with Us
							through the Service.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>To contact you:</strong> To contact you by email, telephone
							calls, SMS, or other equivalent forms of electronic communication, such
							as a mobile app_lication's push notifications regarding updates or
							informative communications related to the functionalities, products or
							contracted services, including the security updates, when necessary or
							reasonable for their implementation.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>To provide you</strong> with news, special offers and general
							information about other goods, services and events which we offer that
							are similar to those that you have already purchased or enquired about
							unless you have opted not to receive such information.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>To manage your requests:</strong> To attend and manage your
							requests to Us.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>For business transfers:</strong> We may use your information to
							evaluate or conduct a merger, divestiture, restructuring,
							reorganization, dissolution, or other sale or transfer of some or all of
							Our assets, whether as a going concern or as part of bankruptcy,
							liquidation, or similar proceeding, in which Personal Data held by Us
							about our Service users is among the assets transferred.
						</p>
					</li>
					<li className="pp_li">
						<p>
							<strong>For other purposes</strong>: We may use your information for
							other purposes, such as data analysis, identifying usage trends,
							determining the effectiveness of our promotional campaigns and to
							evaluate and improve our Service, products, services, marketing and your
							experience.
						</p>
					</li>
				</ul>
				<p>We may share your personal information in the following situations:</p>
				<ul>
					<li className="pp_li">
						<strong>With Service Providers:</strong> We may share your personal
						information with Service Providers to monitor and analyze the use of our
						Service, to contact you.
					</li>
					<li className="pp_li">
						<strong>For business transfers:</strong> We may share or transfer your
						personal information in connection with, or during negotiations of, any
						merger, sale of Company assets, financing, or acquisition of all or a
						portion of Our business to another company.
					</li>
					<li className="pp_li">
						<strong>With Affiliates:</strong> We may share your information with Our
						affiliates, in which case we will require those affiliates to honor this
						Privacy Policy. Affiliates include Our parent company and any other
						subsidiaries, joint venture partners or other companies that We control or
						that are under common control with Us.
					</li>
					<li className="pp_li">
						<strong>With business partners:</strong> We may share your information with
						Our business partners to offer you certain products, services or promotions.
					</li>
					<li className="pp_li">
						<strong>With other users:</strong> when you share personal information or
						otherwise interact in the public areas with other users, such information
						may be viewed by all users and may be publicly distributed outside. If you
						interact with other users or register through a Third-Party Social Media
						Service, your contacts on the Third-Party Social Media Service may see your
						name, profile, pictures and description of your activity. Similarly, other
						users will be able to view descriptions of your activity, communicate with
						you and view your profile.
					</li>
					<li className="pp_li">
						<strong>With your consent</strong>: We may disclose your personal
						information for any other purpose with your consent.
					</li>
				</ul>
				<h2 className="pp_h2">Retention of your Personal Data</h2>
				<p>
					The Company will retain your Personal Data only for as long as is necessary for
					the purposes set out in this Privacy Policy. We will retain and use your
					Personal Data to the extent necessary to comply with our legal obligations (for
					example, if we are required to retain your data to comply with app_licable
					laws), resolve disputes, and enforce our legal agreements and policies.
				</p>
				<p>
					The Company will also retain Usage Data for internal analysis purposes. Usage
					Data is generally retained for a shorter period of time, except when this data
					is used to strengthen the security or to improve the functionality of Our
					Service, or We are legally obligated to retain this data for longer time
					periods.
				</p>
				<h2 className="pp_h2">Transfer of your Personal Data</h2>
				<p>
					your information, including Personal Data, is processed at the Company's
					operating offices and in any other places where the parties involved in the
					processing are located. It means that this information may be transferred to —
					and maintained on — computers located outside of your state, province, country
					or other governmental jurisdiction where the data protection laws may differ
					than those from your jurisdiction.
				</p>
				<p>
					your consent to this Privacy Policy followed by your submission of such
					information represents your agreement to that transfer.
				</p>
				<p>
					The Company will take all steps reasonably necessary to ensure that your data is
					treated securely and in accordance with this Privacy Policy and no transfer of
					your Personal Data will take place to an organization or a country unless there
					are adequate controls in place including the security of your data and other
					personal information.
				</p>
				<h2 className="pp_h2">Disclosure of your Personal Data</h2>
				<h3 className="pp_h3">Business Transactions</h3>
				<p>
					If the Company is involved in a merger, acquisition or asset sale, your Personal
					Data may be transferred. We will provide notice before your Personal Data is
					transferred and becomes subject to a different Privacy Policy.
				</p>
				<h3 className="pp_h3">Law enforcement</h3>
				<p>
					Under certain circumstances, the Company may be required to disclose your
					Personal Data if required to do so by law or in response to valid requests by
					public authorities (e.g. a court or a government agency).
				</p>
				<h3 className="pp_h3">Other legal requirements</h3>
				<p>
					The Company may disclose your Personal Data in the good faith belief that such
					action is necessary to:
				</p>
				<ul>
					<li className="pp_li">Comply with a legal obligation</li>
					<li className="pp_li">
						Protect and defend the rights or property of the Company
					</li>
					<li className="pp_li">
						Prevent or investigate possible wrongdoing in connection with the Service
					</li>
					<li className="pp_li">
						Protect the personal safety of Users of the Service or the public
					</li>
					<li className="pp_li">Protect against legal liability</li>
				</ul>
				<h2 className="pp_h2">Security of your Personal Data</h2>
				<p>
					The security of your Personal Data is important to Us, but remember that no
					method of transmission over the Internet, or method of electronic storage is
					100% secure. While We strive to use commercially acceptable means to protect
					your Personal Data, We cannot guarantee its absolute security.
				</p>
				<h2 className="pp_h2">Children's Privacy</h2>
				<p>
					Our Service does not address anyone under the age of 13. We do not knowingly
					collect personally identifiable information from anyone under the age of 13. If
					you are a parent or guardian and you are aware that your child has provided Us
					with Personal Data, please contact Us. If We become aware that We have collected
					Personal Data from anyone under the age of 13 without verification of parental
					consent, We take steps to remove that information from Our servers.
				</p>
				<p>
					If We need to rely on consent as a legal basis for processing your information
					and your country requires consent from a parent, We may require your parent's
					consent before We collect and use that information.
				</p>
				<h2 className="pp_h2">Links to Other Websites</h2>
				<p>
					Our Service may contain links to other websites that are not operated by Us. If
					you click on a third party link, you will be directed to that third party's
					site. We strongly advise you to review the Privacy Policy of every site you
					visit.
				</p>
				<p>
					We have no control over and assume no responsibility for the content, privacy
					policies or practices of any third party sites or services.
				</p>
				<h2 className="pp_h2">Changes to this Privacy Policy</h2>
				<p>
					We may update Our Privacy Policy from time to time. We will notify you of any
					changes by posting the new Privacy Policy on this page.
				</p>
				<p>
					We will let you know via email and/or a prominent notice on Our Service, prior
					to the change becoming effective and update the &quot;Last updated&quot; date at
					the top of this Privacy Policy.
				</p>
				<p>
					you are advised to review this Privacy Policy periodically for any changes.
					Changes to this Privacy Policy are effective when they are posted on this page.
				</p>
				<h2 className="pp_h2">Contact Us</h2>
				<p>If you have any questions about this Privacy Policy, you can contact us:</p>
				<ul>
					<li className="pp_li">
						<p>By email: 18ucs090@lnmiit.ac.in</p>
					</li>
					<li className="pp_li">
						<p>
							By visiting this page on our website:{' '}
							<a
								href="medipro.com/contactus"
								rel="external nofollow noopener"
								target="_blank"
							>
								medipro.com/contactus
							</a>
						</p>
					</li>
					<li className="pp_li">
						<p>By mail: The LNM Institute Of Information Technology, Jaipur</p>
					</li>
				</ul>
			</div>
		);
	}
}

export default PrivacyPolicy;
